idf_component_register(SRCS
                        "main.c"
                        "network.c"
                        "palm_progress.c"
                    INCLUDE_DIRS
                        "."
                    REQUIRES
                        esp_timer
                        esp_wifi
                        esp_driver_uart
                        nvs_flash
                        lwip
                        locker
                        buzzer
                        display
                        lvgl
                        lvgl_port
                        XST
                        custom
                        generated
                        serve
                    )